name: Rerun the pipeline at the start of each month and update if new data is available

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Extract, transform, load
        run: |
          source("etl.R")
        shell: Rscript {0}

      - name: Commit changes (if any)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "Add new data"
          git push
